#!/data/data/com.termux/files/usr/bin/bash

set -e

add_to_file() {
    grep -qF -- "$1" "$2" || echo "$1" >> "$2"
}

# let termux work in background
termux-wake-lock

# get access to external storage
yes | termux-setup-storage

# install base packages
pkg install -y termux-api net-tools openssh wget tsu tmux p7zip

# setup startup commands
add_to_file 'sshd' ~/.bashrc
add_to_file 'termux-wake-lock' ~/.bashrc

# allow external apps to call termux
sed -i '/allow-external-apps/s/^#*//g' $HOME/.termux/termux.properties
